Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2020-10, with the labels that each got.

#172 Add the new diagnostics for the constraints to the HISTORY.rc
  HISTORY.AGCM.rc.tmpl
Labels: 0 diff

#173 Restore missing forward-slash
  gcm_run.j
Labels: 0 diff, bugfix

#171 Fixes #167 - duplicated pflogger messages
  logging.yaml
Labels: 0 diff trivial, enhancement

#174 Sync develop into main
  HISTORY.AGCM.rc.tmpl
  gcm_run.j
  logging.yaml
Labels: 0 diff

#175 Add commented QSAT logger
  logging.yaml
Labels: 0 diff trivial

#176 Fixes #164. Increase job name limit
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, enhancement

#178 Sync dev into main
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  logging.yaml
  stratchem_setup
Labels: 0 diff
