Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2020-03, with the labels that each got.

#95 Brought the chem setup scripts in line with gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#98 Feature/sdrabenh/fix bugs in fcst scripts
  gcm_forecast.setup
  gcm_forecast.tmpl
  gcm_post.j
  gcm_run.j
Labels: 0 diff, enhancement

#102 Sync develop into master
  .AGCM_VERSION
  CMakeLists.txt
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_archive.j
  gcm_convert.j
  gcm_emip.setup
  gcm_forecast.setup
  gcm_forecast.tmpl
  gcm_moveplot.j
  gcm_plot.tmpl
  gcm_post.j
  gcm_regress.j
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#104 Update CMakeLists.txt: Remove debug print
  CMakeLists.txt
Labels: 0 diff trivial

#106 Update to let MAPL 2 GEOS work with MPT
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, bugfix

#105 Fixes #96. Add model/processor question to setup scripts
  gcm_quickstat.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#108 Sync develop into master
  CMakeLists.txt
  gcm_quickstat.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#109 Bug fix in gcm_forecast.setup
  gcm_forecast.setup
Labels: 0 diff trivial
