Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2020-07, with the labels that each got.

#139 Add gwd_import to checkpoint/restart
  AGCM.rc.tmpl
Labels: 0 diff, Non 0-diff

#138 Update Aerosol Chemistry BCs CHMDIR variable to match vertical levels
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#141 Add new questions to gcm_setup for chosing microphysics and hydrostat…
  AGCM.rc.tmpl
  fvcore_layout.rc
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#143 Feature/yury/coupled regress
  gcm_regress.j
Labels: 0 diff trivial, enhancement

#145 feature/sdrabenh/enable_NL_EMIP
  gcm_emip.setup
  gcm_run.j
  gcm_setup
Labels: 0 diff, enhancement

#144 Removed S2S history template with confusing name.
  HISTORY.S2S.rc.tmpl
Labels: 0 diff trivial, bugfix

#146 Sync dev -> main
  HISTORY.S2S.rc.tmpl
  gcm_emip.setup
  gcm_regress.j
  gcm_run.j
  gcm_setup
Labels: 0 diff, enhancement
