Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2020-04, with the labels that each got.

#112 Fixes #111. Use different ALLREDUCE algorithm
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, bugfix

#110 Bugfix/narnold1/#201 scm fixes
  scm_setup
Labels: 0 diff trivial, bugfix

#107 New Surface parameter resource file
  AGCM.rc.tmpl
  gcm_run.j
  gcm_setup
Labels: 0 diff, enhancement

#119 Fixes #118. Change Intel MPI GATHERV algorithm
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, bugfix

#121 Fixes #120. Allows another user to run gcm_setup
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#117 Fixes #114. Add link option
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
