Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2021-12, with the labels that each got.

#273 Feature/rtodling/v1 5 6 geosit
  HISTORY_GEOSIT.rc.tmpl
Labels: enhancement, 0 diff

#275 Sync develop into main
  HISTORY_GEOSIT.rc.tmpl
Labels: 0 diff

#277 Change default config to use new orbit parameters
  AGCM.rc.tmpl
Labels: Non 0-diff

#281 Sync develop into main
  AGCM.rc.tmpl
Labels: Non 0-diff

#279 Add mpich to list of MPI stacks
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff trivial

#280 Update NAS nodes for TOSS
  CMakeLists.txt
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#283 Sync develop into main
  CMakeLists.txt
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
