Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2021-04, with the labels that each got.

#212 Change setup scripts depending on HYDROSTATIC build
  CMakeLists.txt
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#213 Sync dev into main
  CMakeLists.txt
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#214 Update MAPL logger
  logging.yaml
Labels: 0 diff trivial

#154 Update AGCM.rc.tmpl NRL Solar File
  AGCM.rc.tmpl
Labels: Non 0-diff, enhancement
