Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2021-11, with the labels that each got.

#267 Add automatic PR for develop to MAPL3 branch
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
Labels: 0 diff trivial

#269 MAPL V3 FLAP usage simplification
  GEOSgcm.F90
Labels: 0 diff trivial, MAPL3

#261 Fix for setup scripts
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#263 WSUB fix in gmichem_setup
  gmichem_setup
Labels: 0 diff trivial

#265 Feature/rtodling/v1 5 4 onl xoffl flags
  AGCM.rc.tmpl
  HISTORY.rc.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_convert.j
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_run_CPLFCST360S2S.j
  gcm_run_CPLFCST360S2Sall.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff structural

#262 Add code to install source tarfile
  CMakeLists.txt
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#272 Sync develop into main
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
  AGCM.rc.tmpl
  CMakeLists.txt
  HISTORY.rc.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_convert.j
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_run_CPLFCST360S2S.j
  gcm_run_CPLFCST360S2Sall.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
