Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2021-09, with the labels that each got.

#249 Updates for Cascade Lake at NCCS
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#252 remove CNFROOTC when running CNCLM40
  gcm_run.j
Labels: bugfix, 0 diff

#254 Update LICENSE to Apache, other license changes
  COPYRIGHT
  LICENSE
  LICENSE-NOSA
  README.md
Labels: documentation, 0 diff trivial
