Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2021-05, with the labels that each got.

#222 Remove BULK_SST alias for TS_FOUND in HISTORies used in model (only) simulations
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM6.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY_S2S.rc.tmpl
Labels: 0 diff structural, documentation

#223 Updates needed for GEOSadas MAPL 2 work
  AGCM.rc.tmpl
  GCMPROG.rc.tmpl
  HISTORY.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#221 Add IOSERVER code to forecast
  gcm_forecast.tmpl
Labels: 0 diff

#217 Detect if splitting is needed in more files
  gcm_convert.j
  gcm_forecast.tmpl
  gcm_regress.j
Labels: 0 diff

#224 Change Default Land to Icarus-NLv3
  gcm_forecast.tmpl
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: Non 0-diff

#225 Sync develop into main
  AGCM.rc.tmpl
  CONTRIBUTING.md
  GCMPROG.rc.tmpl
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM6.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.rc.tmpl
  HISTORY_S2S.rc.tmpl
  gcm_convert.j
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: Non 0-diff, bugfix

#226 Fix for running Old Land BCs
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, bugfix

#227 GitFlow: Merge Main hotfix into Develop
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#228 follow MAPL's change to add a new MAPL_CapOptions constructor
  GEOSgcm.F90
Labels: 0 diff

#229 Sync develop into main
  GEOSgcm.F90
Labels: 0 diff
