Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2022-12, with the labels that each got.

#380 Move to use GitHub Action for Label Enforcement
  .github/workflows/enforce-labels.yml
Labels: 0 diff

#356 R21C HISTORY output specs (precip, land, landice, ...)
  HISTORY_R21C.rc.tmpl
Labels: Contingent - DNA, 0 diff trivial

#382 Feature/yury/aogcm mom5 hist HISTORY.AOGCM-MOM5.rc.tmpl made consistent with MOM6 and AMIP templates
  HISTORY.AOGCM-MOM5.rc.tmpl
Labels: enhancement, 0 diff structural

#383 Bugfix/yury/aogcm notilehist `regrid_exch: tile_hist.data` was removed from history template
  gcm_run.j
Labels: enhancement, 0 diff structural

#387 Sync develop into main
  .circleci/config.yml
  .github/workflows/enforce-labels.yml
  AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY_GMICHEM.rc.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
