Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2022-03, with the labels that each got.

#302 Add support for AMIP.20C
  AGCM.rc.tmpl
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  scm_setup
  stratchem_setup
Labels: 0 diff

#304 Sync develop into main
  AGCM.rc.tmpl
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  scm_setup
  stratchem_setup
Labels: bugfix, 0 diff

#305 Bugfix for undefined date in gcm_regress.j
  gcm_regress.j
Labels: bugfix, 0 diff

#289 To gather memory and detailed timing information
  fvcore_layout.rc
Labels: enhancement, 0 diff

#297 Feature/rtodling/gcm 1 12 4 tskinice realfix
  GCMPROG.rc.tmpl
  HISTFDDAL.rc.tmpl
  HISTORY.rc.tmpl
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
  HISTORY_GEOSIT.rc.tmpl
  HISTORY_MERRA2-DD.rc.tmpl
  HISTORY_MERRA2.rc.tmpl
Labels: bugfix, 0 diff

#301 Feature/rtodling/geosit history1
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.21z.tmpl
  HISTORY_GEOSIT.rc.tmpl
Labels: 0 diff trivial

#307 Feature/tclune/#306 profiling with pflogger
  .gitignore
  logging.yaml
Labels: 0 diff trivial

#310 Sync develop into main
  .gitignore
  GCMPROG.rc.tmpl
  HISTFDDAL.rc.tmpl
  HISTORY.rc.tmpl
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
  HISTORY_GEOSIT.rc.tmpl
  HISTORY_MERRA2-DD.rc.tmpl
  HISTORY_MERRA2.rc.tmpl
  fvcore_layout.rc
  gcm_regress.j
  logging.yaml
Labels: 0 diff

#312 Updates for Spack Support, Round 2
  CMakeLists.txt
Labels: 0 diff
