Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-02, with the labels that each got.

#570 Improve readability
  gcm_run.j
Labels: bugfix, 0 diff trivial

#576 M21C updates
  HISTORY_R21C.rc.tmpl
Labels: 0 diff

#577 sync in changes from v1.9.6 and other updates
  .circleci/config.yml
  AGCM.rc.tmpl
  HISTORY_R21C.rc.tmpl
Labels: 0 diff

#569 Initialize USE_WAVES to 0
  AGCM.rc.tmpl
  gcm_run.j
Labels: 0 diff

#573 Use nccmp, add readers/writers test to regress
  gcm_regress.j
Labels: 0 diff

#575 Disable Catchment-CN4.5 land model option (LSM_CHOICE=3) for GCM simulations
  AGCM.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff trivial

#578 add surface forcing lfo_Nx+- to HISTORY.rc.tmpl
  HISTORY.rc.tmpl
Labels: 0 diff trivial

#580 Use CMake to determine MPI Stack
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#582 Feature/pnorris/rrtmgp validation
  HISTORY.RADVAL.rc.tmpl
Labels: 0 diff structural
