Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-12, with the labels that each got.

#663 update land-related collections in HISTORY.rc.tmpl to match M21C file specs
  HISTORY.rc.tmpl
Labels: documentation, bugfix, 0 diff

#661 v12: Fixes #653. Update default ocean to CS for C90+
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#662 v12: Updates and fixes for SCM
  scm_run.j
  scm_setup
Labels: Non 0-diff

#666 v11: Convert all setup >>>-vars to @-vars
  .circleci/config.yml
  AGCM.rc.tmpl
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.BENCHMARK.rc.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_forecast.tmpl
  gcm_run.j
  gcm_run_CPLFCST360S2S.j
  gcm_run_CPLFCST360S2Sall.j
  gcm_run_benchmark.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: 0 diff

#665 Added support for GEOSgigatraj gridcomp
  AGCM.rc.tmpl
  CMakeLists.txt
  gcm_run.j
Labels: enhancement, 0 diff

#669 v12: Add protections for TSE_TMPDIR
  gcm_forecast.tmpl
  gcm_run.j
  gcm_setup
Labels: 0 diff
