Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-08, with the labels that each got.

#635 Sync develop into main
  HISTORY.rc.tmpl
  HISTORY_GMICHEM.rc.tmpl
  HISTORY_STRATCHEM.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: 0 diff

#640 v12: Update NX, NY, DT, Intel MPI Flags, OpenMP regress
  .editorconfig
  gcm_regress.j
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, Non 0-diff

#637 M21C: add definition of land constants collections into HISTORY_R21C.rc.tmpl
  HISTORY_R21C.rc.tmpl
Labels: enhancement, 0 diff
