Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-07, with the labels that each got.

#618 Addresses the lack of 001 in the variable names for SS001 and DU001
  HISTORY_R21C.rc.tmpl
Labels: 0 diff

#623 Bugfix for issue #622
  linkbcs.tmpl
Labels: bugfix, 0 diff trivial

#629 M21C History updates
  .circleci/config.yml
  HISTORY_R21C.rc.tmpl
Labels: 0 diff trivial

#630 M21C exports and LONG_NAMES for land water and energy balances
  HISTORY_R21C.rc.tmpl
Labels: 0 diff

#633 Updates for R21C for SLES15 on NCCS
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#621 exports for land water and energy balances
  HISTORY.rc.tmpl
Labels: bugfix, 0 diff

#626 Fixes #625. TMPHIST not created if cloning
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#627 Update GMI and StratChem HISTORY
  HISTORY_GMICHEM.rc.tmpl
  HISTORY_STRATCHEM.rc.tmpl
Labels: 0 diff trivial
