Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-04, with the labels that each got.

#599 Minor update to GMI and StratChem setup scripts
  gmichem_setup
  stratchem_setup
Labels: 0 diff trivial

#591 Replaced Default $HOMEDIR pathway with user's $NOBACKUP inside gcm_setup
  gcm_setup
Labels: 0 diff, 0 diff trivial

#544 Support for new linkbcs + handful of smaller changes
  AGCM.rc.tmpl
  gcm_forecast.tmpl
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: 0 diff
