Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2024-01, with the labels that each got.

#553 Update MPT flags for use with MAPL 2.44 (current develop)
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#543 Add tuning flags for Open MPI and Intel MPI on SLES15 at NCCS
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#557 Update circleci-tools orb to v2
  .circleci/config.yml
Labels: 0 diff trivial

#560 NWP Updates
  AGCM.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#562 Sync develop into main
  .circleci/config.yml
  AGCM.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff, Non 0-diff

#558 Allow others to make coupled experiments
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: enhancement, 0 diff

#556 Default to Cascade Lake at NCCS for SLES12
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#564 Updates for R21C
  AGCM.rc.tmpl
  HISTORY_R21C.rc.tmpl
Labels: 0 diff trivial

#552 WMMA
  construct_extdata_yaml_list.py
  gcm_run.j
Labels: enhancement, 0 diff

#565 Minor fixes of v2.3.0 for ADAS
  AGCM.rc.tmpl
  GCMPROG.rc.tmpl
  HISTFDDA.rc.tmpl
  HISTFDDAL.rc.tmpl
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.AOGCM_MITgcm.rc.tmpl
  HISTORY.BENCHMARK.rc.tmpl
  HISTORY.rc.tmpl
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff trivial

#567 Sync develop into main
  AGCM.rc.tmpl
  GCMPROG.rc.tmpl
  HISTFDDA.rc.tmpl
  HISTFDDAL.rc.tmpl
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.AOGCM_MITgcm.rc.tmpl
  HISTORY.BENCHMARK.rc.tmpl
  HISTORY.rc.tmpl
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
  construct_extdata_yaml_list.py
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_run.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
