Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2025-01, with the labels that each got.

#672 v12: Move to use generic RRTMGP data location
  .circleci/config.yml
  AGCM.rc.tmpl
Labels: 0 diff

#668 Adding Data Atmosphere from S2S to mainline gcm
  AGCM.rc.tmpl
  HISTORY.DATAATM.rc.tmpl
  construct_extdata_yaml_list.py
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: enhancement, 0 diff

#676 v11: Fixes for SCM
  scm_run.j
  scm_setup
Labels: bugfix, 0 diff

#568 Updates to enable jemalloc build
  CMakeLists.txt
Labels: 0 diff

#673 Sync develop into main
  .circleci/config.yml
  AGCM.rc.tmpl
  CMakeLists.txt
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.BENCHMARK.rc.tmpl
  HISTORY.DATAATM.rc.tmpl
  HISTORY.rc.tmpl
  construct_extdata_yaml_list.py
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_forecast.tmpl
  gcm_run.j
  gcm_run_CPLFCST360S2S.j
  gcm_run_CPLFCST360S2Sall.j
  gcm_run_benchmark.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  scm_run.j
  scm_setup
  stratchem_setup
Labels: 0 diff

#679 v11: Copy over weight files for SCM
  scm_setup
Labels: 0 diff

#681 v11: Add Cas for SLES15; Add back IMPI flags on SLES15
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#678 Move aerosol fluxes to adg. NOTE THIS SHOULD BE IN FPP!
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
Labels: 0 diff structural

#684 Sync develop into main
  .github/workflows/push-to-develop.yml
  .github/workflows/validate_yaml_files.yml
  HISTORY_FP.rc.03z.tmpl
  HISTORY_FP.rc.09z.tmpl
  HISTORY_FP.rc.15z.tmpl
  HISTORY_FP.rc.21z.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  scm_setup
  stratchem_setup
Labels: 0 diff
