Repository GEOS-ESM/GEOSgcm_App, pull requests merged in 2025-02, with the labels that each got.

#682 v12: Add Cas for SLES15; Add back IMPI flags on SLES15
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#690 v12: Remove Skylake at NCCS
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#691 v12: Fixes for v13 gwd_internal_rst handling
  .github/workflows/validate_yaml_files.yml
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_run_benchmark.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: 0 diff

#667 v12: Convert all setup >>>-vars to @-vars
  AGCM.rc.tmpl
  HISTORY.AGCM.rc.tmpl
  HISTORY.AOGCM-MOM5.rc.tmpl
  HISTORY.AOGCM.rc.tmpl
  HISTORY.BENCHMARK.rc.tmpl
  gcm_CPLFCST360NM2_setup
  gcm_CPLFCST360S2S_setup
  gcm_CPLFCST360S2Sallsetup
  gcm_forecast.tmpl
  gcm_run.j
  gcm_run_CPLFCST360S2S.j
  gcm_run_CPLFCST360S2Sall.j
  gcm_run_benchmark.j
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  linkbcs.tmpl
  stratchem_setup
Labels: 0 diff

#688 v11: Remove Skylake at NCCS
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff

#689 Add label, @LDAS_INCR, to AGCM.rc.tmpl
  AGCM.rc.tmpl
Labels: 0 diff trivial

#696 v12: Fix lazy sed for RRTMGP
  gcm_forecast.tmpl
  gcm_regress.j
  gcm_run.j
  gcm_run.j-new_rst_approach
  gcm_run_benchmark.j
Labels: bugfix, 0 diff

#698 Sync develop into main
  AGCM.rc.tmpl
  gcm_setup
  geoschemchem_setup
  gmichem_setup
  stratchem_setup
Labels: 0 diff
